###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - './src:/application'
        environment:
            - POSTGRES_USER=symfony
            - POSTGRES_PASSWORD=symfony
            - POSTGRES_DB=symfony
        ports:
            - '18004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './src:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '18000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './src:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
